# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ManualBuild

on:
  workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#env:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

#    - name: Add MSBuild to PATH
#      uses: microsoft/setup-msbuild@v1.1.3

#    - name: Restore NuGet packages
#      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Create artifact
      run: .\package.bat

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wolf_remix_files
        path: .\build\*
        include-hidden-files: true
